apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx-app
    minReadySeconds: 5
    template:
      metadata:
        labels:
          app: nginx-app
      spec:
        containers:
          - name: nginx
            image: nginx
            ports:
              - containerPort: 80