apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingtest
  labels:
    app: pinger
spec:
  replicas: 3 # for 3 nodes
  selector:
    matchLabels:
      app: pinger
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pinger
    spec:
      containers:
        - image: nigelpoulton/acg-web:0.1
          name: ubuntu-ctr
          command:
            - /bin/bash
            - "-c"
            - "sleep 60m"
          imagePullPolicy: IfNotPresent
      restartPolicy: Always